feat(01-building-blocks): added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,18 +1,17 @@
 name: 01 - Building Blocks
-on:
-  workflow_dispatch:
+on:  workflow_dispatch
 jobs:
-  echo-hello:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Say Hello
-        run: echo "Hello, World!"
-  echo-goodbye:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Failed step
-        run: |
-          echo "I will fail" 
-          exit 0
-      - name: Say Goodbye
-        run: echo "Goodbye, World!"
+    echo-hello:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Say Hello
+          run: echo "Hello, World!"
+    echo-goodbye:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Failed step
+          run: |
+            echo "I will fail" 
+            exit 1
+        - name: Say Goodbye
+          run: echo "Goodbye, World!"
